name: Process building blocks

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: opengeospatial/bblocks-postprocess/.github/workflows/process-bblocks.yml@master
    with:
      base-url: https://maytetoscano.github.io/bblocks-uav-biodiversity
      items-dir: _sources
      generated-docs-path: build/generateddocs
      annotated-path: build/annotated
      test-outputs-path: build/tests
      register-file: build/register.json
      clean: true
      deploy-viewer: true
