- name: Run bblocks postprocess (generate site)
  run: |
    docker run --pull=always --rm --workdir /workspace \
      -v "$PWD:/workspace" \
      ghcr.io/opengeospatial/bblocks-postprocess \
      --clean true \
      --output-dir build-local/generateddocs

- name: Upload Pages artifact
  uses: actions/upload-pages-artifact@v3
  with:
    path: build-local/generateddocs
